# Math Basics

# 1)Vectors

In [4]:
## Assigning values to vector x 

x = [1, 2, 3, 4, 5]
#display the output.
x

[1, 2, 3, 4, 5]

In [11]:
# import numpy package
import numpy as np
#assigning x with the array values
x = np.array([1, 2, 3, 4, 5])
#display the output x
print(x)
#display the type of x
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# 2)Matrices

In [12]:
## assign values to matrix m.

m = np.array([[1, 5, 2],
              [4, 7, 4],
              [2, 0, 9]])

# display matrix m
print(m)

# know the dimension/size of matrix m
print(m.shape)

[[1 5 2]
 [4 7 4]
 [2 0 9]]
(3, 3)


# 2a)Matrix Transpose

In [13]:
# transpose the matrix m and assign the values to matrix n.
print('Matrix Transpose:\n', m.transpose(), '\n')

Matrix Transpose:
 [[1 4 2]
 [5 7 0]
 [2 4 9]] 



# 2b)Matrix Determinant

In [14]:
# calculating the matrix determinant and assigining the value to n.
print ('Matrix Determinant:', np.linalg.det(m), '\n')

Matrix Determinant: -105.00000000000006 



# 2c)Matrix Inverse

In [15]:
## for matrix m apply the matrix inverse function and assign to matrix n.
m_inv = np.linalg.inv(m)
print ('Matrix inverse:\n', m_inv, '\n')

Matrix inverse:
 [[-0.6         0.42857143 -0.05714286]
 [ 0.26666667 -0.04761905 -0.03809524]
 [ 0.13333333 -0.0952381   0.12380952]] 



# 2d) Matrix Identity

In [16]:
# identity matrix (result of matrix x matrix_inverse)
iden_m =  np.dot(m, m_inv)
iden_m = np.round(np.abs(iden_m), 0)

#display the output
print ('Product of matrix and its inverse:\n', iden_m)

Product of matrix and its inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 2e)Eigen decomposition

In [18]:
# eigen decomposition of matrix m
m = np.array([[1, 5, 2],
              [4, 7, 4],
              [2, 0, 9]])

#Assigning the eigen values to varaibles.
eigen_vals, eigen_vecs = np.linalg.eig(m)

#Display Eigen values
print('Eigen Values:', eigen_vals, '\n')
#Display Eigen vectors
print('Eigen Vectors:\n', eigen_vecs)

Eigen Values: [-1.32455532 11.32455532  7.        ] 

Eigen Vectors:
 [[-0.91761521  0.46120352 -0.46829291]
 [ 0.35550789  0.79362022 -0.74926865]
 [ 0.17775394  0.39681011  0.46829291]]


# 2f)Single Value Decomposition

In [20]:
# Assigning array values to m.
m = np.array([[1, 5, 2],
              [4, 7, 4],
              [2, 0, 9]])

# doing single value decomposition
U, S, VT = np.linalg.svd(m)

#Display the mentioned text
print ('Getting SVD outputs:-\n')
#Display the value of U
print('U:\n', U, '\n')
#Display the value of S
print('S:\n', S, '\n')
#Display the value of VT
print('VT:\n', VT, '\n')

Getting SVD outputs:-

U:
 [[ 0.3831556  -0.39279153  0.83600634]
 [ 0.68811254 -0.48239977 -0.54202545]
 [ 0.61619228  0.78294653  0.0854506 ]] 

S:
 [12.10668383  6.91783499  1.25370079] 

VT:
 [[ 0.36079164  0.55610321  0.74871798]
 [-0.10935467 -0.7720271   0.62611158]
 [-0.92621323  0.30777163  0.21772844]] 



# 3)Descriptive Statistics

In [23]:
# import scipy package
import scipy as sp
# import numpy package
import numpy as np
# import stats package from scipy package
from scipy import stats 

# get the data information
nums = np.random.randint(1,20, size=(1,15))[0]
#Display the data.
print('Data: ', nums)

Data:  [ 6 12  5 16  8  6 11 15  6  8  7 15 13 19  1]


In [24]:
# Descriptive statistic results
# Display the mean value of the nums varaible
print ('Mean:', sp.mean(nums))
# Display the median value of the nums varaible
print ('Median:', sp.median(nums))
# Display the mode value of the nums varaible
print ('Mode:', sp.stats.mode(nums))
# Display the standard deviation value of the nums varaible
print ('Standard Deviation:', sp.std(nums))
# Display the variance value of the nums varaible
print ('Variance:', sp.var(nums))
# Display the skew value of the nums varaible
print ('Skew:', sp.stats.skew(nums))
# Display the Kurtosis value of the nums varaible
print ('Kurtosis:', sp.stats.kurtosis(nums))

Mean: 9.866666666666667
Median: 8.0
Mode: ModeResult(mode=array([6]), count=array([3]))
Standard Deviation: 4.8424052792893
Variance: 23.448888888888884
Skew: 0.16599519781562802
Kurtosis: -0.8921216764831481
