# Math Basics

# 1)Vectors

In [4]:
## Assigning values to vector x 

x = [1, 2, 3, 4, 5]
#display the output.
x

[1, 2, 3, 4, 5]

In [11]:
# import numpy package
import numpy as np
#assigning x with the array values
x = np.array([1, 2, 3, 4, 5])
#display the output x
print(x)
#display the type of x
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# 2)Matrices

In [12]:
## assign values to matrix m.

m = np.array([[1, 5, 2],
              [4, 7, 4],
              [2, 0, 9]])

# display matrix m
print(m)

# know the dimension/size of matrix m
print(m.shape)

[[1 5 2]
 [4 7 4]
 [2 0 9]]
(3, 3)


# 2a)Matrix Transpose

In [13]:
# transpose the matrix m and assign the values to matrix n.
print('Matrix Transpose:\n', m.transpose(), '\n')

Matrix Transpose:
 [[1 4 2]
 [5 7 0]
 [2 4 9]] 



# 2b)Matrix Determinant

In [14]:
# calculating the matrix determinant and assigining the value to n.
print ('Matrix Determinant:', np.linalg.det(m), '\n')

Matrix Determinant: -105.00000000000006 



# 2c)Matrix Inverse

In [15]:
## for matrix m apply the matrix inverse function and assign to matrix n.
m_inv = np.linalg.inv(m)
print ('Matrix inverse:\n', m_inv, '\n')

Matrix inverse:
 [[-0.6         0.42857143 -0.05714286]
 [ 0.26666667 -0.04761905 -0.03809524]
 [ 0.13333333 -0.0952381   0.12380952]] 



# 2d) Matrix Identity

In [16]:
# identity matrix (result of matrix x matrix_inverse)
iden_m =  np.dot(m, m_inv)
iden_m = np.round(np.abs(iden_m), 0)

#display the output
print ('Product of matrix and its inverse:\n', iden_m)

Product of matrix and its inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 2e)Eigen decomposition

In [18]:
# eigen decomposition of matrix m
m = np.array([[1, 5, 2],
              [4, 7, 4],
              [2, 0, 9]])

#Assigning the eigen values to varaibles.
eigen_vals, eigen_vecs = np.linalg.eig(m)

#Display Eigen values
print('Eigen Values:', eigen_vals, '\n')
#Display Eigen vectors
print('Eigen Vectors:\n', eigen_vecs)

Eigen Values: [-1.32455532 11.32455532  7.        ] 

Eigen Vectors:
 [[-0.91761521  0.46120352 -0.46829291]
 [ 0.35550789  0.79362022 -0.74926865]
 [ 0.17775394  0.39681011  0.46829291]]


# 2f)Single Value Decomposition

In [20]:
# Assigning array values to m.
m = np.array([[1, 5, 2],
              [4, 7, 4],
              [2, 0, 9]])

# doing single value decomposition
U, S, VT = np.linalg.svd(m)

#Display the mentioned text
print ('Getting SVD outputs:-\n')
#Display the value of U
print('U:\n', U, '\n')
#Display the value of S
print('S:\n', S, '\n')
#Display the value of VT
print('VT:\n', VT, '\n')

Getting SVD outputs:-

U:
 [[ 0.3831556  -0.39279153  0.83600634]
 [ 0.68811254 -0.48239977 -0.54202545]
 [ 0.61619228  0.78294653  0.0854506 ]] 

S:
 [12.10668383  6.91783499  1.25370079] 

VT:
 [[ 0.36079164  0.55610321  0.74871798]
 [-0.10935467 -0.7720271   0.62611158]
 [-0.92621323  0.30777163  0.21772844]] 



# 3)Descriptive Statistics

In [23]:
# import scipy package
import scipy as sp
# import numpy package
import numpy as np
# import stats package from scipy package
from scipy import stats 

# get the data information
nums = np.random.randint(1,20, size=(1,15))[0]
#Display the data.
print('Data: ', nums)

Data:  [ 6 12  5 16  8  6 11 15  6  8  7 15 13 19  1]


In [24]:
# Descriptive statistic results
# Display the mean value of the nums varaible
print ('Mean:', sp.mean(nums))
# Display the median value of the nums varaible
print ('Median:', sp.median(nums))
# Display the mode value of the nums varaible
print ('Mode:', sp.stats.mode(nums))
# Display the standard deviation value of the nums varaible
print ('Standard Deviation:', sp.std(nums))
# Display the variance value of the nums varaible
print ('Variance:', sp.var(nums))
# Display the skew value of the nums varaible
print ('Skew:', sp.stats.skew(nums))
# Display the Kurtosis value of the nums varaible
print ('Kurtosis:', sp.stats.kurtosis(nums))

Mean: 9.866666666666667
Median: 8.0
Mode: ModeResult(mode=array([6]), count=array([3]))
Standard Deviation: 4.8424052792893
Variance: 23.448888888888884
Skew: 0.16599519781562802
Kurtosis: -0.8921216764831481


# Predicting Student Recommendation

# Data Retrieval

In [2]:
#import panda package
import pandas as pd

# turn off the warning messages
pd.options.mode.chained_assignment = None  # default option is  'warn'

# retieving data from the file "student records" to "df"
df = pd.read_csv('student_records.csv')

#display the file
df


Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

# Data Preparation

## Feature extraction and engineering

In [8]:
# assigning a common name to all the feature vraiables
feature_names = ['OverallGrade', 'Obedient', 'ResearchScore', 'ProjectScore']
training_features = df[feature_names]

# display feature varaibles without mentioning all the varaible names.
training_features

OverallGrade Obedient  ResearchScore  ProjectScore
0            A        Y             90            85
1            C        N             85            51
2            F        N             10            17
3            B        Y             75            71
4            E        N             20            30
5            A        Y             92            79
6            B        Y             60            59
7            C        Y             75            33

In [9]:
#assigning the varaible Recommend to the outcome_name
outcome_name = ['Recommend']

#The table df has a outcome_label assigned now
outcome_labels = df[outcome_name]

# display outcome labels
outcome_labels

Recommend
0       Yes
1       Yes
2        No
3        No
4        No
5       Yes
6        No
7        No

In [11]:
# Based on type assign both the numeric and categorical features to a varaible
numeric_feature_names = ['ResearchScore', 'ProjectScore']
categoricial_feature_names = ['OverallGrade', 'Obedient']

## Numeric Feature Scaling

In [14]:
#import the package StandardScaler from sklearn and assign it to ss.

from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

# performing fit scaler on numeric features
ss.fit(training_features[numeric_feature_names])
       
# scaling numeric features by transform
(training_features[numeric_feature_names]) = ss.transform(training_features[numeric_feature_names])
       
#the above two steps are called fit_transform used for the initial fitting of parameters but it also returns a transformed output.

# display the updated featureset
training_features

C:\Users\thispc\Anaconda3\Anaconda\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\thispc\Anaconda3\Anaconda\lib\site-packages\ipykernel_launcher.py:10: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  # Remove the CWD from sys.path while we load stuff.


OverallGrade Obedient  ResearchScore  ProjectScore
0            A        Y       0.899583      1.376650
1            C        N       0.730648     -0.091777
2            F        N      -1.803390     -1.560203
3            B        Y       0.392776      0.772004
4            E        N      -1.465519     -0.998746
5            A        Y       0.967158      1.117516
6            B        Y      -0.114032      0.253735
7            C        Y       0.392776     -0.869179

## Engineering Categorical Features

In [15]:
# converting the column of catergorical variables to row based on the no. of categories in the varaible
training_features = pd.get_dummies(training_features, columns=categoricial_feature_names)

# display newly engineering features
training_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_B  \
0       0.899583      1.376650               1               0   
1       0.730648     -0.091777               0               0   
2      -1.803390     -1.560203               0               0   
3       0.392776      0.772004               0               1   
4      -1.465519     -0.998746               0               0   
5       0.967158      1.117516               1               0   
6      -0.114032      0.253735               0               1   
7       0.392776     -0.869179               0               0   

   OverallGrade_C  OverallGrade_E  OverallGrade_F  Obedient_N  Obedient_Y  
0               0               0               0           0           1  
1               1               0               0           1           0  
2               0               0               1           1           0  
3               0               0               0           0           1  
4               0               1               0           1           0  
5               0               0               0           0           1  
6               0               0               0           0           1  
7               1               0               0           0           1

In [17]:
# create a varaible which displays only categorical feature variables
categorical_engineered_features = list(set(training_features.columns) - set(numeric_feature_names))

#display the categorical feature variable
categorical_engineered_features

['OverallGrade_B',
 'OverallGrade_A',
 'OverallGrade_C',
 'OverallGrade_E',
 'OverallGrade_F',
 'Obedient_Y',
 'Obedient_N']

# Modeling

In [18]:
#import logistic regression package from sklearn
from sklearn.linear_model import LogisticRegression
import numpy as np

#assign the function Logistic regression to lr
lr = LogisticRegression() 

# fitting the model to the training data is essentially the training part of modeling process.
model = lr.fit(training_features, np.array(outcome_labels['Recommend']))

# display model parameters
model

C:\Users\thispc\Anaconda3\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

## Model Evaluation

In [19]:
# simple evaluation on training data to make it ready for predictions
pred_labels = model.predict(training_features)
actual_labels = np.array(outcome_labels['Recommend'])

# evaluate model performance by importing classification and accuracy score from sklearn
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

#Display the accuracy score after calculation and the classification report
print('Accuracy:', float(accuracy_score(actual_labels, pred_labels))*100, '%')
print('Classification Stats:')
print(classification_report(actual_labels, pred_labels))

Accuracy: 100.0 %
Classification Stats:
              precision    recall  f1-score   support

          No       1.00      1.00      1.00         5
         Yes       1.00      1.00      1.00         3

   micro avg       1.00      1.00      1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8



## Model Deployment 

In [22]:
#import joblib package from sklearn
from sklearn.externals import joblib

#import os package
import os

# copythe models to be deployed on your server
if not os.path.exists('Model'):
    os.mkdir('Model')
if not os.path.exists('Scaler'):
    os.mkdir('Scaler') 

# dump the model into server
joblib.dump(model, r'Model/model.pickle') 
joblib.dump(ss, r'Scaler/scaler.pickle') 

['Scaler/scaler.pickle']

## Prediction in Action

In [24]:
# load model and scaler objects in varaibles model and scaler respectively
model = joblib.load(r'Model/model.pickle')
scaler = joblib.load(r'Scaler/scaler.pickle')

In [25]:
#data retrieval and assigning to varaible new_data
new_data = pd.DataFrame([{'Name': 'Nathan', 'OverallGrade': 'F', 'Obedient': 'N', 'ResearchScore': 30, 'ProjectScore': 20},
                  {'Name': 'Thomas', 'OverallGrade': 'A', 'Obedient': 'Y', 'ResearchScore': 78, 'ProjectScore': 80}])
new_data = new_data[['Name', 'OverallGrade', 'Obedient', 'ResearchScore', 'ProjectScore']]

#display new data
new_data

Name OverallGrade Obedient  ResearchScore  ProjectScore
0  Nathan            F        N             30            20
1  Thomas            A        Y             78            80

In [26]:
## data preparation for new data
prediction_features = new_data[feature_names]

# scaling of new sata
prediction_features[numeric_feature_names] = scaler.transform(prediction_features[numeric_feature_names])

# engineering categorical variables of new data
prediction_features = pd.get_dummies(prediction_features, columns=categoricial_feature_names)

# display feature set of new data
prediction_features

C:\Users\thispc\Anaconda3\Anaconda\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """


ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_F  Obedient_N  \
0      -1.127647     -1.430636               0               1           1   
1       0.494137      1.160705               1               0           0   

   Obedient_Y  
0           0  
1           1

In [28]:
# add missing categorical feature columns
current_categorical_engineered_features = set(prediction_features.columns) - set(numeric_feature_names)
missing_features = set(categorical_engineered_features) - current_categorical_engineered_features
for feature in missing_features:
    # add zeros since feature is absent in these data samples
    prediction_features[feature] = [0] * len(prediction_features) 

# view final feature set
prediction_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_F  Obedient_N  \
0      -1.127647     -1.430636               0               1           1   
1       0.494137      1.160705               1               0           0   

   Obedient_Y  OverallGrade_E  OverallGrade_B  OverallGrade_C  
0           0               0               0               0  
1           1               0               0               0

In [29]:
## predict using model prepared before
predictions = model.predict(prediction_features)

## display the results for new data
new_data['Recommend'] = predictions

#display the output
new_data

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0  Nathan            F        N             30            20        No
1  Thomas            A        Y             78            80       Yes